version: '20.10.17'
services:
  api:
    build: 
      context: ./Dockerfile-dev
    ports:
      - "8080:8080"
    links:
      - mongo
  db_app:
    image: mongo:5.0.10-focal
    ports:
      - "8081:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gabriel
      - MONGO_INITDB_ROOT_PASSWORD=1234