version: '20.10.17'
services:
  api:
    build: ./
    ports:
      - "8080:8080"
    links:
      - "mongo"
  db_app:
    image: mongo:5.0.10-focal
    ports:
      - "8081:8080"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "gabriel"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "1234"
      ME_CONFIG_MONGODB_URL: "mongodb://gabriel:1234@mongo:8080/app_pedido_dev"